### ISSUE TITLE
Should this plugin be running on every build or just once?

### ISSUE THREAD

**Issue by WebShapedBiz** [11ty/eleventy-upgrade-help#2]
Sorry for the stupid question but I don't get if I should run this plugin once and then remove it from the project, or should I leave it running as any other plugin.

Cheers.

**Comment by paulshryock** [comment]
> should run this plugin once and then remove it from the project, or should I leave it running as any other plugin

@WebShapedBiz, it seems like this plugin is intended to be left running like a regular plugin (rather than run only once). However, I think it's mainly useful as a temporary assistance while upgrading to a major version until you have a chance to handle [the changes](https://github.com/11ty/eleventy-upgrade-help#features) yourself--then you would remove the plugin.

**Comment by WebShapedBiz** [comment]
I think I got it. Thank you for your time and effort @paulshryock

**Comment by bobmonsour** [comment]
The readme says: "After your upgrade is complete and you’ve removed all of the violations/warnings from your output, delete the plugin from your package.json and .eleventy.js configuration file."
